# Generated by Django 4.2.6 on 2024-07-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringDescription',
            fields=[
                ('task_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.taskdescription')),
                ('model_type', models.TextField(max_length=10)),
                ('type_selection_visibility', models.BooleanField()),
                ('distance_visibility', models.BooleanField()),
                ('cluster_slider_visibility', models.BooleanField()),
                ('linkage_visibility', models.BooleanField()),
                ('silhouette_coefficient_visibility', models.BooleanField()),
                ('elbow_plot_visibility', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetworkDescription',
            fields=[
                ('task_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.taskdescription')),
                ('max_epochs', models.IntegerField()),
                ('max_layers', models.IntegerField()),
                ('max_nodes', models.IntegerField()),
                ('iterations_slider_visibility', models.BooleanField()),
                ('lr_slider_visibility', models.BooleanField()),
                ('normalization_visibility', models.BooleanField()),
                ('af_visibility', models.BooleanField(default=False)),
                ('decision_boundary_visibility', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='row',
            name='activations_on',
        ),
        migrations.RemoveField(
            model_name='row',
            name='epochs',
        ),
        migrations.RemoveField(
            model_name='row',
            name='games_data',
        ),
        migrations.RemoveField(
            model_name='row',
            name='learning_rate',
        ),
        migrations.RemoveField(
            model_name='row',
            name='network_input',
        ),
        migrations.RemoveField(
            model_name='row',
            name='normalization',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='af_visibility',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='decision_boundary_visibility',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='iterations_slider_visibility',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='lr_slider_visibility',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='max_epochs',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='max_layers',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='max_nodes',
        ),
        migrations.RemoveField(
            model_name='taskdescription',
            name='normalization_visibility',
        ),
        migrations.AddField(
            model_name='row',
            name='inputs',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='short_name',
            field=models.CharField(default='[name here]', max_length=20),
            preserve_default=False,
        ),
    ]
