# Generated by Django 4.2.6 on 2024-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_clusteringdescription_neuralnetworkdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdescription',
            name='file_name',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='function_name',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
