# Generated by Django 4.2.6 on 2024-07-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_taskdescription_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('task_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='external_link', serialize=False, to='backend.taskdescription')),
                ('url', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='row',
            old_name='inputs',
            new_name='in_out',
        ),
        migrations.AlterField(
            model_name='clusteringdescription',
            name='task_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clustering_description', serialize=False, to='backend.taskdescription'),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='task_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='neural_network_description', serialize=False, to='backend.taskdescription'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('task_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.taskdescription')),
            ],
        ),
    ]
