# Generated by Django 4.2.6 on 2024-07-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_externallink_rename_inputs_row_in_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='task_description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='backend.taskdescription'),
            preserve_default=False,
        ),
    ]
