# Generated by Django 4.2.6 on 2024-07-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_externallink_rename_inputs_row_in_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicsDescription',
            fields=[
                ('task_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basics_description', serialize=False, to='backend.taskdescription')),
                ('order_slider_visibility', models.BooleanField()),
                ('max_order', models.IntegerField()),
                ('min_order', models.IntegerField()),
                ('datapoints_field_visibility', models.BooleanField()),
                ('features_field_visibility', models.BooleanField()),
                ('type_menu_visibility', models.BooleanField()),
                ('type_menu_options', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SVMDescription',
            fields=[
                ('task_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='svm_description', serialize=False, to='backend.taskdescription')),
                ('rbf_visibility', models.BooleanField()),
                ('c_slider_visibility', models.BooleanField()),
                ('gamma_slider_visibility', models.BooleanField()),
                ('highlight_support_vectors', models.BooleanField()),
            ],
        ),
    ]
