# Generated by Django 4.2.6 on 2024-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_basicsdescription_svmdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteringdescription',
            name='model_type',
        ),
        migrations.AddField(
            model_name='clusteringdescription',
            name='type_selection_options',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='svmdescription',
            name='accuracy_visibility',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svmdescription',
            name='f1_visibility',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='basicsdescription',
            name='max_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basicsdescription',
            name='min_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basicsdescription',
            name='type_menu_options',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='decision_boundary_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='iterations_slider_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='lr_slider_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='max_epochs',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='max_layers',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='max_nodes',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='normalization_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='row',
            name='in_out',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='dataset',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='file_name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='function_name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='n_inputs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='n_outputs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdescription',
            name='type',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
