# Generated by Django 4.2.6 on 2024-07-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_taskdescription_other_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetworkdescription',
            name='sensitive_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
