# Generated by Django 4.2.6 on 2024-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_neuralnetworkdescription_sensitive_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetworkdescription',
            name='af_options',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='neuralnetworkdescription',
            name='optimizer_options',
            field=models.TextField(default='', max_length=50),
        ),
    ]
