# Generated by Django 4.2.6 on 2024-10-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_neuralnetworkdescription_af_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
