# Generated by Django 4.2.6 on 2024-10-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_levelstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='af_options',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='neuralnetworkdescription',
            name='optimizer_options',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
